language: cpp
before_install:
  - sudo mv Arduino15 /Applications/Library
  - sudo mv Arduino.app /Applications

install: true
script:
  - arduino --verify --board AZ3166:stm32f4:MXCHIP_AZ3166 $PWD/testForTravis/testForTravis.ino
  notifications:
  email:
    on_success: change
    on_failure: change


